apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cineapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/linatireche/cineapp-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cineapp-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cineapp-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cineapp-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: cineapp-config
                  key: DB_USER
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cineapp-config
                  key: PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cineapp-secret
                  key: DB_PASSWORD
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cineapp-secret
                  key: TMDB_API_KEY
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
