apiVersion: v1
kind: ConfigMap
metadata:
  name: cineapp-config
  namespace: cineapp
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "cineapp"
  DB_USER: "postgres"
  PORT: "3000"